services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ${METASTORE_DB}
      POSTGRES_USER: ${METASTORE_DB_USER}
      POSTGRES_PASSWORD: ${METASTORE_DB_PASSWORD}
    ports:
      - "${METASTORE_DB_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \"$${POSTGRES_USER}\" -d \"$${POSTGRES_DB}\""]
      interval: 10s
      timeout: 5s
      retries: 5

  hive-metastore:
    image: seathegood/hive-metastore:latest
    pull_policy: never
    environment:
      METASTORE_DB: ${METASTORE_DB}
      METASTORE_DB_USER: ${METASTORE_DB_USER}
      METASTORE_DB_PASSWORD: ${METASTORE_DB_PASSWORD}
      METASTORE_DB_HOST: ${METASTORE_DB_HOST}
      METASTORE_DB_PORT: ${METASTORE_DB_PORT}
      METASTORE_PORT: ${METASTORE_PORT}
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "${METASTORE_PORT:-9083}:9083"
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s