name: Check for New Hive Releases

on:
  schedule:
    - cron: '0 2 * * *'  # Run daily at 2am UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check-hive-version:
    runs-on: ubuntu-latest
    env:
      DOCKERFILE_PATH: Dockerfile
      VERSION_FILE: versions.json
      HIVE_DOWNLOAD_BASE: https://dlcdn.apache.org/hive
      GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
      GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Get latest Hive version
        id: hive
        run: |
          latest=$(curl -s https://downloads.apache.org/hive/ | grep -oP 'hive-\K[0-9.]+(?=/)' | sort -V | tail -1)
          echo "latest=$latest" >> $GITHUB_OUTPUT

      - name: Get current version from Dockerfile
        id: current
        run: |
          current=$(grep -oP 'ARG HIVE_VERSION=\K[0-9.]+' $DOCKERFILE_PATH)
          echo "current=$current" >> "$GITHUB_OUTPUT"

      - name: Check if update is needed
        run: |
          if [ "${{ steps.hive.outputs.latest }}" == "${{ steps.current.outputs.current }}" ]; then
            echo "Hive is already up to date: ${{ steps.current.outputs.current }}"
            exit 0
          fi

      - name: Compare versions
        if: always()
        run: |
          echo "New version found: ${{ steps.hive.outputs.latest }}"
          echo "Current version: ${{ steps.current.outputs.current }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Update Dockerfile and versions.json on new branch
        if: steps.hive.outputs.latest != steps.current.outputs.current
        run: |
          git checkout main
          git pull origin main
          branch="hive-update-${{ steps.hive.outputs.latest }}"

          if git ls-remote --exit-code --heads origin "$branch"; then
            git fetch origin "$branch":"$branch"
            git checkout "$branch"
            git reset --hard origin/"$branch"
          else
            git checkout -b "$branch"
          fi

          sed -i "s/ARG HIVE_VERSION=.*/ARG HIVE_VERSION=${{ steps.hive.outputs.latest }}/" $DOCKERFILE_PATH

          # Update SCHEMA_VERSION in entrypoint.sh and healthcheck.sh
          schema_version=$(echo "${{ steps.hive.outputs.latest }}" | cut -d'.' -f1,2)
          sed -i "s/SCHEMA_VERSION=\"[0-9.]*\"/SCHEMA_VERSION=\"$schema_version\"/" entrypoint.sh
          sed -i "s/SCHEMA_VERSION=\"[0-9.]*\"/SCHEMA_VERSION=\"$schema_version\"/" healthcheck.sh
          git add entrypoint.sh healthcheck.sh

          # Fetch SHA256 and update versions.json
          sha=$(curl -s $HIVE_DOWNLOAD_BASE/hive-${{ steps.hive.outputs.latest }}/apache-hive-${{ steps.hive.outputs.latest }}-bin.tar.gz.sha256 | cut -d' ' -f1)
          jq --arg v "${{ steps.hive.outputs.latest }}" --arg s "$sha" '.hive[$v] = {sha256: $s}' $VERSION_FILE > tmp.json && mv tmp.json $VERSION_FILE

          git add $VERSION_FILE

      - name: Verify updated version strings
        if: steps.hive.outputs.latest != steps.current.outputs.current
        run: |
          grep HIVE_VERSION $DOCKERFILE_PATH
          grep SCHEMA_VERSION entrypoint.sh
          grep SCHEMA_VERSION healthcheck.sh
          jq '.hive' versions.json

      - name: Show git diff for debugging
        if: steps.hive.outputs.latest != steps.current.outputs.current
        run: git status && git diff

      - name: Commit and push changes
        if: steps.hive.outputs.latest != steps.current.outputs.current
        run: |
          git config --local user.email "${{ env.GIT_USER_EMAIL }}"
          git config --local user.name "${{ env.GIT_USER_NAME }}"
          git commit --allow-empty -am "Update to Hive ${{ steps.hive.outputs.latest }}"
          git push origin "$branch"

      - name: Create Pull Request
        if: steps.hive.outputs.latest != steps.current.outputs.current
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update to Hive ${{ steps.hive.outputs.latest }}"
          title: "chore: update to Hive ${{ steps.hive.outputs.latest }}"
          body: |
            This pull request updates Hive to version ${{ steps.hive.outputs.latest }}.
            Please review and test before merging.
          branch: hive-update-${{ steps.hive.outputs.latest }}
          base: main

      - name: Summary
        if: steps.hive.outputs.latest != steps.current.outputs.current
        run: |
          echo "### Hive version update" >> $GITHUB_STEP_SUMMARY
          echo "- Current: ${{ steps.current.outputs.current }}" >> $GITHUB_STEP_SUMMARY
          echo "- New: ${{ steps.hive.outputs.latest }}" >> $GITHUB_STEP_SUMMARY
