name: CI

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY_IMAGE: ghcr.io/${{ github.repository }}
  CACHE_DIR: /tmp/.buildx-cache
  NETWORK_NAME: ci-net

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Load environment variables
        run: |
          set -o allexport
          source .env || true
          set +o allexport

      - name: Validate required env vars
        run: |
          if [ -z "$REGISTRY_IMAGE" ]; then
            echo "REGISTRY_IMAGE is not set. Make sure it is in your .env file or defined in the workflow."
            exit 1
          fi

      - name: Set up Docker with containerd
        uses: docker/setup-docker-action@v4.0.0
        with:
          daemon-config: |
            {
              "features": {
                "containerd-snapshotter": true
              }
            }

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.1.0
        with:
          driver: docker-container
          driver-opts: image=moby/buildkit:buildx-stable-1
          buildkitd-flags: --debug
          install: true
          use: true

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: ${{ env.CACHE_DIR }}
          key: ${{ runner.os }}-buildx-${{ hashFiles('Dockerfile', 'versions.json') }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Create Docker network
        run: docker network create ${{ env.NETWORK_NAME }}

      - name: Build Docker image
        run: |
          docker buildx build \
            --cache-from=type=local,src=${{ env.CACHE_DIR }} \
            --cache-to=type=local,dest=${{ env.CACHE_DIR }},mode=max \
            -t ${{ env.REGISTRY_IMAGE }}:ci-test \
            --load .

      - name: Push Docker image (only on main)
        if: github.ref == 'refs/heads/main'
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker buildx build \
            --cache-from=type=local,src=${{ env.CACHE_DIR }} \
            --cache-to=type=local,dest=${{ env.CACHE_DIR }},mode=max \
            -t ${{ env.REGISTRY_IMAGE }}:latest \
            --push .

      - name: Start PostgreSQL
        run: |
          docker run -d --network ${{ env.NETWORK_NAME }} \
            --name pg-test \
            -e POSTGRES_DB=${{ env.POSTGRES_DB }} \
            -e POSTGRES_USER=${{ env.POSTGRES_USER }} \
            -e POSTGRES_PASSWORD=${{ env.POSTGRES_PASSWORD }} \
            postgres:15

      - name: Wait for PostgreSQL
        run: |
          for i in {1..10}; do
            docker exec pg-test pg_isready -U ${{ env.POSTGRES_USER }} && exit 0 || sleep 3
          done
          docker logs pg-test
          exit 1

      - name: Run Hive Metastore
        run: |
          docker run -d --network ${{ env.NETWORK_NAME }} \
            --name metastore-test \
            -e METASTORE_DB_HOST=pg-test \
            -e METASTORE_DB_PORT=${{ env.METASTORE_DB_PORT }} \
            -e METASTORE_DB_NAME=${{ env.POSTGRES_DB }} \
            -e METASTORE_DB_USER=${{ env.POSTGRES_USER }} \
            -e METASTORE_DB_PASSWORD=${{ env.POSTGRES_PASSWORD }} \
            -p ${{ env.METASTORE_PORT }}:${{ env.METASTORE_PORT }} \
            ${{ env.REGISTRY_IMAGE }}:ci-test

      - name: Wait for Metastore health
        run: |
          for i in {1..10}; do
            health=$(docker inspect --format='{{.State.Health.Status}}' metastore-test)
            if [ "$health" = "healthy" ]; then exit 0; fi
            sleep 5
          done
          docker inspect metastore-test
          docker logs metastore-test
          exit 1

      - name: Verify files inside image
        run: |
          docker run --rm ${{ env.REGISTRY_IMAGE }}:ci-test test -f /opt/hive/lib/postgresql-jdbc.jar
          docker run --rm ${{ env.REGISTRY_IMAGE }}:ci-test test -f /opt/hive/conf/hive-site.xml

      - name: Validate versions.json
        run: jq -e 'has("hive") and has("postgresql")' versions.json

      - name: Lint shell scripts
        run: |
          sudo apt-get update && sudo apt-get install -y shellcheck
          shellcheck docker-entrypoint.sh healthcheck.sh

      - name: Save logs
        if: always()
        run: |
          mkdir -p artifacts
          docker logs metastore-test 2>&1 | sed -E 's/(password=)[^&"]+/\1****/g' | sed -E 's/(jdbc:[^ ]+):\/\/[^ ]+/\1:\/\/REDACTED/g' > artifacts/metastore.log || true
          docker logs pg-test 2>&1 | sed -E 's/(password=)[^&"]+/\1****/g' | sed -E 's/(jdbc:[^ ]+):\/\/[^ ]+/\1:\/\/REDACTED/g' > artifacts/postgres.log || true

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4.3.1
        with:
          name: ci-logs
          path: artifacts/

      - name: Clean up containers
        if: always()
        run: |
          docker rm -f metastore-test pg-test || true
          docker network rm ${{ env.NETWORK_NAME }} || true
