name: CI

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  CACHE_DIR: /tmp/.buildx-cache
  NETWORK_NAME: ci-net

jobs:
  test-hive-metastore:
    runs-on: ubuntu-latest
    env:
      PLATFORM_TAG: amd64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Load environment from .env file
        run: |
          echo "Loading env vars into GITHUB_ENV"
          grep -v '^#' .env | while read -r line; do
            echo "$line" >> $GITHUB_ENV
          done

      - name: Set METASTORE_DB_HOST dynamically
        run: echo "METASTORE_DB_HOST=pg-test-${{ env.PLATFORM_TAG }}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.1.0
        with:
          install: true

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: ${{ env.CACHE_DIR }}
          key: buildx-${{ env.PLATFORM_TAG }}-${{ hashFiles('Dockerfile', 'versions.json') }}
          restore-keys: |
            buildx-${{ env.PLATFORM_TAG }}-
            buildx-

      - name: Build image
        run: |
          docker buildx build \
            --platform linux/${{ env.PLATFORM_TAG }} \
            --output=type=docker \
            --cache-from=type=local,src=${{ env.CACHE_DIR }} \
            --cache-to=type=local,dest=${{ env.CACHE_DIR }}-new \
            --build-arg PLATFORM_TAG=${{ env.PLATFORM_TAG }} \
            --tag ci-local/hive-metastore:test \
            .
          rm -rf ${{ env.CACHE_DIR }}
          mv ${{ env.CACHE_DIR }}-new ${{ env.CACHE_DIR }}

      - name: Create Docker network
        run: docker network create ${{ env.NETWORK_NAME }}

      - name: Start PostgreSQL
        run: |
          docker run -d --network ${{ env.NETWORK_NAME }} \
            --name pg-test-${{ env.PLATFORM_TAG }} \
            -e POSTGRES_USER=${{ env.METASTORE_DB_USER }} \
            -e POSTGRES_PASSWORD=${{ env.METASTORE_DB_PASSWORD }} \
            -e POSTGRES_DB=${{ env.METASTORE_DB }} \
            -p ${{ env.METASTORE_DB_PORT }}:${{ env.METASTORE_DB_PORT }} \
            postgres:15

      - name: Wait for PostgreSQL
        run: |
          for i in {1..10}; do
            docker exec pg-test-${{ env.PLATFORM_TAG }} pg_isready -U ${{ env.METASTORE_DB_USER }} -d ${{ env.METASTORE_DB }} && exit 0 || sleep 3
          done
          docker logs pg-test-${{ env.PLATFORM_TAG }}
          exit 1

      - name: Run Hive Metastore
        run: |
          docker run -d --platform linux/${{ env.PLATFORM_TAG }} --network ${{ env.NETWORK_NAME }} \
            --name metastore-test-${{ env.PLATFORM_TAG }} \
            --env-file .env \
            -e METASTORE_DB_HOST=${{ env.METASTORE_DB_HOST }} \
            --health-start-period=360s \
            -p ${{ env.METASTORE_PORT }}:${{ env.METASTORE_PORT }} \
            ci-local/hive-metastore:test

      - name: Wait for Hive to become healthy
        run: |
          echo "Waiting for container to start..."
          for i in {1..30}; do
            status=$(docker inspect --format='{{.State.Status}}' metastore-test-${{ env.PLATFORM_TAG }})
            echo "Attempt $i: Container status is $status"
            if [ "$status" = "running" ]; then
              echo "Container is running, proceeding with health checks..."
              break
            fi
            sleep 5
          done
          echo "Delaying additional 120 seconds for Hive initialization..."
          sleep 120
          echo "Checking health status of Hive Metastore"
          for i in {1..20}; do
            health=$(docker inspect --format='{{json .State.Health}}' metastore-test-${{ env.PLATFORM_TAG }} | jq -r '.Status')
            echo "Attempt $i: Health status is $health"
            if [ "$health" = "healthy" ]; then
              echo "Hive Metastore is healthy"
              exit 0
            fi
            sleep 10
          done
          echo "Health check failed after maximum retries. Dumping logs:"
          docker inspect metastore-test-${{ env.PLATFORM_TAG }}
          docker logs metastore-test-${{ env.PLATFORM_TAG }}
          exit 1

      - name: Clean up containers
        run: |
          docker rm -f metastore-test-${{ env.PLATFORM_TAG }} || true
          docker rm -f pg-test-${{ env.PLATFORM_TAG }} || true
