name: CI

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  CACHE_DIR: /tmp/.buildx-cache
  NETWORK_NAME: ci-net

jobs:
  test-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
    env:
      PLATFORM_TAG: ${{ matrix.platform == 'linux/amd64' && 'amd64' || 'arm64' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Load environment from .env file
        run: |
          echo "Loading env vars into GITHUB_ENV"
          grep -v '^#' .env | while read -r line; do
            echo "$line" >> $GITHUB_ENV
          done

      - name: Set METASTORE_DB_HOST dynamically
        run: echo "METASTORE_DB_HOST=pg-test-matrix-${{ env.PLATFORM_TAG }}" >> $GITHUB_ENV


      - name: Set up Docker with containerd
        uses: docker/setup-docker-action@v4.0.0
        with:
          daemon-config: |
            {
              "features": {
                "containerd-snapshotter": true
              }
            }

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.1.0
        with:
          driver: docker-container
          driver-opts: image=moby/buildkit:buildx-stable-1
          buildkitd-flags: --debug
          install: true
          use: true

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: ${{ env.CACHE_DIR }}
          key: buildx-${{ env.PLATFORM_TAG }}-${{ hashFiles('Dockerfile', 'versions.json') }}
          restore-keys: |
            buildx-${{ env.PLATFORM_TAG }}-
            buildx-

      - name: Create Docker network
        run: docker network create ${{ env.NETWORK_NAME }}

      - name: Build and push Docker image
        run: |
          docker buildx build \
            --platform ${{ matrix.platform }} \
            --output=type=docker \
            --cache-from=type=local,src=${{ env.CACHE_DIR }} \
            --cache-to=type=local,dest=${{ env.CACHE_DIR }}-new \
            --build-arg PLATFORM_TAG=${{ env.PLATFORM_TAG }} \
            --tag ci-local/hive-metastore:ci-test-${{ env.PLATFORM_TAG }} \
            .
          rm -rf ${{ env.CACHE_DIR }}
          mv ${{ env.CACHE_DIR }}-new ${{ env.CACHE_DIR }}

      - name: Start PostgreSQL
        run: |
          docker run -d --network ${{ env.NETWORK_NAME }} \
            --name pg-test-matrix-${{ env.PLATFORM_TAG }} \
            -e POSTGRES_USER=${{ env.METASTORE_DB_USER }} \
            -e POSTGRES_PASSWORD=${{ env.METASTORE_DB_PASSWORD }} \
            -e POSTGRES_DB=${{ env.METASTORE_DB }} \
            -p ${{ env.METASTORE_DB_PORT }}:${{ env.METASTORE_DB_PORT }} \
            postgres:15

      - name: Wait for PostgreSQL
        run: |
          for i in {1..10}; do
            docker exec pg-test-matrix-${{ env.PLATFORM_TAG }} pg_isready -U ${{ env.METASTORE_DB_USER }} -d ${{ env.METASTORE_DB }} && exit 0 || sleep 3
          done
          docker logs pg-test-matrix-${{ env.PLATFORM_TAG }}
          exit 1

      - name: Run Hive Metastore
        run: |
          docker run -d --platform ${{ matrix.platform }} --network ${{ env.NETWORK_NAME }} \
            --name metastore-test-matrix-${{ env.PLATFORM_TAG }} \
            --env-file .env \
            -e METASTORE_DB_HOST=${{ env.METASTORE_DB_HOST }} \
            -p ${{ env.METASTORE_PORT }}:${{ env.METASTORE_PORT }} \
            ci-local/hive-metastore:ci-test-${{ env.PLATFORM_TAG }}

      - name: Check health status
        run: |
          echo "Waiting for container to start..."
          for i in {1..30}; do
            status=$(docker inspect --format='{{.State.Status}}' metastore-test-matrix-${{ env.PLATFORM_TAG }})
            echo "Attempt $i: Container status is $status"
            if [ "$status" = "running" ]; then
              echo "Container is running, proceeding with health checks..."
              break
            fi
            sleep 5
          done
          echo "Delaying additional 180 seconds for Hive initialization..."
          sleep 180
          echo "Checking health status of Hive Metastore on platform ${{ env.PLATFORM_TAG }}"
          for i in {1..20}; do
            health=$(docker inspect --format='{{json .State.Health}}' metastore-test-matrix-${{ env.PLATFORM_TAG }} | jq -r '.Status')
            echo "Attempt $i: Health status is $health"
            if [ "$health" = "healthy" ]; then
              echo "Hive Metastore is healthy"
              exit 0
            fi
            sleep 10
          done
          echo "Health check failed after maximum retries. Dumping logs:"
          docker inspect metastore-test-matrix-${{ env.PLATFORM_TAG }}
          docker logs metastore-test-matrix-${{ env.PLATFORM_TAG }}
          exit 1

      - name: Validate versions.json
        if: matrix.platform == 'linux/amd64'
        run: jq -e 'has("hive") and has("postgresql")' versions.json

      - name: Install ShellCheck
        if: matrix.platform == 'linux/amd64'
        run: sudo apt-get update && sudo apt-get install -y shellcheck

      - name: Lint shell scripts
        if: matrix.platform == 'linux/amd64'
        run: shellcheck docker-entrypoint.sh healthcheck.sh

      - name: Clean up containers
        if: always()
        run: |
          docker rm -f metastore-test-matrix-${{ env.PLATFORM_TAG }} || true
          docker rm -f pg-test-matrix-${{ env.PLATFORM_TAG }} || true

      - name: Save logs
        if: always()
        run: |
          mkdir -p artifacts
          docker logs metastore-test-matrix-${{ env.PLATFORM_TAG }} 2>&1 | sed -E 's/(password=)[^&"]+/\1****/g' | sed -E 's/(jdbc:[^ ]+):\/\/[^ ]+/\1:\/\/REDACTED/g' > artifacts/metastore-matrix-${{ env.PLATFORM_TAG }}.log || true
          docker logs pg-test-matrix-${{ env.PLATFORM_TAG }} 2>&1 | sed -E 's/(password=)[^&"]+/\1****/g' | sed -E 's/(jdbc:[^ ]+):\/\/[^ ]+/\1:\/\/REDACTED/g' > artifacts/postgres-matrix-${{ env.PLATFORM_TAG }}.log || true

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ci-logs-matrix-${{ env.PLATFORM_TAG }}
          path: artifacts/
