name: CI

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  CACHE_DIR: /tmp/.buildx-cache
  NETWORK_NAME: ci-net

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
    env:
      PLATFORM_TAG: ${{ matrix.platform == 'linux/amd64' && 'amd64' || 'arm64' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Load environment from .env file
        run: |
          echo "Loading env vars into GITHUB_ENV"
          while IFS='=' read -r key value; do
            if [[ ! "$key" =~ ^# && -n "$key" ]]; then
              echo "$key=$value" >> $GITHUB_ENV
            fi
          done < .env

      - name: Set METASTORE_DB_HOST dynamically
        run: echo "METASTORE_DB_HOST=pg-test-matrix-${{ env.PLATFORM_TAG }}" >> $GITHUB_ENV

      - name: Override REGISTRY_IMAGE for CI use
        run: echo "REGISTRY_IMAGE=ci-local/hive-metastore" >> $GITHUB_ENV

      - name: Set up Docker with containerd
        uses: docker/setup-docker-action@v4.0.0
        with:
          daemon-config: |
            {
              "features": {
                "containerd-snapshotter": true
              }
            }

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.1.0
        with:
          driver: docker-container
          driver-opts: image=moby/buildkit:buildx-stable-1
          buildkitd-flags: --debug
          install: true
          use: true

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: ${{ env.CACHE_DIR }}
          key: buildx-${{ env.PLATFORM_TAG }}-${{ hashFiles('Dockerfile', 'versions.json') }}
          restore-keys: |
            buildx-${{ env.PLATFORM_TAG }}-
            buildx-

      - name: Create Docker network
        run: docker network create ${{ env.NETWORK_NAME }}

      - name: Build Docker image
        run: |
          docker buildx build \
            --platform ${{ matrix.platform }} \
            --output=type=docker \
            --cache-from=type=local,src=/tmp/.buildx-cache \
            --cache-to=type=local,dest=/tmp/.buildx-cache-new \
            --tag ${{ env.REGISTRY_IMAGE }}:ci-test-${{ env.PLATFORM_TAG }} \
            .
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Save Docker image to tarball
        run: |
          docker save ${{ env.REGISTRY_IMAGE }}:ci-test-${{ env.PLATFORM_TAG }} -o hive-metastore-${{ env.PLATFORM_TAG }}.tar

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: hive-metastore-image-${{ env.PLATFORM_TAG }}
          path: hive-metastore-${{ env.PLATFORM_TAG }}.tar

  test-matrix:
    needs: build-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
    env:
      PLATFORM_TAG: ${{ matrix.platform == 'linux/amd64' && 'amd64' || 'arm64' }}
    steps:
      - name: Download Docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: hive-metastore-image-${{ env.PLATFORM_TAG }}
          path: .

      - name: Load Docker image
        run: docker load -i hive-metastore-${{ env.PLATFORM_TAG }}.tar

      - name: Load environment from .env file
        run: |
          echo "Loading env vars into GITHUB_ENV"
          while IFS='=' read -r key value; do
            if [[ ! "$key" =~ ^# && -n "$key" ]]; then
              echo "$key=$value" >> $GITHUB_ENV
            fi
          done < .env

      - name: Set METASTORE_DB_HOST dynamically
        run: echo "METASTORE_DB_HOST=pg-test-matrix-${{ env.PLATFORM_TAG }}" >> $GITHUB_ENV

      - name: Override REGISTRY_IMAGE for CI use
        run: echo "REGISTRY_IMAGE=ci-local/hive-metastore" >> $GITHUB_ENV

      - name: Create Docker network
        run: docker network create ${{ env.NETWORK_NAME }}

      - name: Start PostgreSQL
        run: |
          docker run -d --network ${{ env.NETWORK_NAME }} \
            --name pg-test-matrix-${{ env.PLATFORM_TAG }} \
            --env-file .env \
            -p ${{ env.METASTORE_DB_PORT }}:${{ env.METASTORE_DB_PORT }} \
            postgres:15

      - name: Wait for PostgreSQL
        run: |
          for i in {1..10}; do
            docker exec pg-test-matrix-${{ env.PLATFORM_TAG }} pg_isready -U ${{ env.POSTGRES_USER }} && exit 0 || sleep 3
          done
          docker logs pg-test-matrix-${{ env.PLATFORM_TAG }}
          exit 1

      - name: Run Hive Metastore
        run: |
          docker run -d --platform ${{ matrix.platform }} --network ${{ env.NETWORK_NAME }} \
            --name metastore-test-matrix-${{ env.PLATFORM_TAG }} \
            --env-file .env \
            -e METASTORE_DB_HOST=${{ env.METASTORE_DB_HOST }} \
            -p ${{ env.METASTORE_PORT }}:${{ env.METASTORE_PORT }} \
            ${{ env.REGISTRY_IMAGE }}:ci-test-${{ env.PLATFORM_TAG }}

      - name: Check health status
        run: |
          echo "Checking health status of Hive Metastore on platform ${{ env.PLATFORM_TAG }}"
          for i in {1..20}; do
            health=$(docker inspect --format='{{.State.Health.Status}}' metastore-test-matrix-${{ env.PLATFORM_TAG }})
            echo "Attempt $i: Health status is $health"
            if [ "$health" = "healthy" ]; then
              echo "Hive Metastore is healthy"
              exit 0
            fi
            sleep 10
          done
          echo "Health check failed after maximum retries. Dumping logs:"
          docker inspect metastore-test-matrix-${{ env.PLATFORM_TAG }}
          docker logs metastore-test-matrix-${{ env.PLATFORM_TAG }}
          exit 1

      - name: Validate versions.json
        if: matrix.platform == 'linux/amd64'
        run: jq -e 'has("hive") and has("postgresql")' versions.json

      - name: Install ShellCheck
        if: matrix.platform == 'linux/amd64'
        run: sudo apt-get update && sudo apt-get install -y shellcheck

      - name: Lint shell scripts
        if: matrix.platform == 'linux/amd64'
        run: shellcheck docker-entrypoint.sh healthcheck.sh

      - name: Clean up containers
        if: always()
        run: |
          docker rm -f metastore-test-matrix-${{ env.PLATFORM_TAG }} || true
          docker rm -f pg-test-matrix-${{ env.PLATFORM_TAG }} || true

      - name: Save logs
        if: always()
        run: |
          mkdir -p artifacts
          docker logs metastore-test-matrix-${{ env.PLATFORM_TAG }} 2>&1 | sed -E 's/(password=)[^&"]+/\1****/g' | sed -E 's/(jdbc:[^ ]+):\/\/[^ ]+/\1:\/\/REDACTED/g' > artifacts/metastore-matrix-${{ env.PLATFORM_TAG }}.log || true
          docker logs pg-test-matrix-${{ env.PLATFORM_TAG }} 2>&1 | sed -E 's/(password=)[^&"]+/\1****/g' | sed -E 's/(jdbc:[^ ]+):\/\/[^ ]+/\1:\/\/REDACTED/g' > artifacts/postgres-matrix-${{ env.PLATFORM_TAG }}.log || true

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ci-logs-matrix-${{ env.PLATFORM_TAG }}
          path: artifacts/
